#!/usr/bin/env python3
from __future__ import annotations

import argparse

from doctor import cmd_doctor
from git_ops import cmd_git
from indexes import cmd_index, cmd_index_open_questions
from migration import cmd_migrate_legacy, cmd_migrate_v3
from notes import cmd_breakdown_design, cmd_output, cmd_write_note
from project import cmd_init, cmd_resolve
from query import cmd_query
from questions import cmd_add_question, cmd_list_questions, cmd_match_questions, cmd_resolve_question
from registry import cmd_list_projects, cmd_register_project, cmd_registry_doctor, cmd_unregister_project


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)

    def add_resolution_args(command: argparse.ArgumentParser) -> None:
        command.add_argument("--project-root")
        command.add_argument("--knowledge-root")
        command.add_argument("--cwd")
        command.add_argument("--registry-file")

    init = sub.add_parser("init")
    init.add_argument("--project", required=True)
    init.add_argument("--source")
    add_resolution_args(init)
    init.set_defaults(func=cmd_init)
    resolve = sub.add_parser("resolve")
    add_resolution_args(resolve)
    resolve.set_defaults(func=cmd_resolve)
    write_note = sub.add_parser("write-note")
    write_note.add_argument("--project", required=True)
    write_note.add_argument("--perspective", required=True)
    write_note.add_argument("--title", required=True)
    write_note.add_argument("--content-file", required=True)
    write_note.add_argument("--lifecycle-stage")
    write_note.add_argument("--source-type")
    add_resolution_args(write_note)
    write_note.set_defaults(func=cmd_write_note)
    index = sub.add_parser("index")
    index.add_argument("--project", required=True)
    add_resolution_args(index)
    index.set_defaults(func=cmd_index)
    query = sub.add_parser("query")
    query.add_argument("--project", required=True)
    query.add_argument("--target", required=True, choices=["implementation_spec", "implementation_plan", "execution", "customer_spec", "bidding", "deployment", "operation"])
    query.add_argument("--query", required=True)
    query.add_argument("--mode", default="authority")
    query.add_argument("--limit", type=int, default=20)
    query.add_argument("--include-background", action="store_true")
    add_resolution_args(query)
    query.set_defaults(func=cmd_query)
    index_oq = sub.add_parser("index-open-questions")
    index_oq.add_argument("--project", required=True)
    add_resolution_args(index_oq)
    index_oq.set_defaults(func=cmd_index_open_questions)
    git = sub.add_parser("git")
    git.add_argument("--project", required=True)
    add_resolution_args(git)
    git.add_argument("git_args", nargs=argparse.REMAINDER)
    git.set_defaults(func=cmd_git)
    doctor = sub.add_parser("doctor")
    doctor.add_argument("--project", required=True)
    add_resolution_args(doctor)
    doctor.set_defaults(func=cmd_doctor)
    output = sub.add_parser("output")
    output.add_argument("--project", required=True)
    output.add_argument("--title", required=True)
    output.add_argument("--content-file", required=True)
    output.add_argument("--output-file")
    add_resolution_args(output)
    output.set_defaults(func=cmd_output)
    breakdown = sub.add_parser("breakdown-design")
    breakdown.add_argument("--project", required=True)
    breakdown.add_argument("--input", required=True)
    breakdown.add_argument("--parts")
    breakdown.add_argument("--language", default="same-as-source")
    add_resolution_args(breakdown)
    breakdown.set_defaults(func=cmd_breakdown_design)
    add_question = sub.add_parser("add-question")
    add_question.add_argument("--project", required=True)
    add_question.add_argument("--perspective", required=True)
    add_question.add_argument("--title", required=True)
    add_question.add_argument("--content-file", required=True)
    add_question.add_argument("--trigger-terms", default="")
    add_question.add_argument("--source-note-ids", default="")
    add_resolution_args(add_question)
    add_question.set_defaults(func=cmd_add_question)
    list_questions = sub.add_parser("list-questions")
    list_questions.add_argument("--project", required=True)
    list_questions.add_argument("--status")
    list_questions.add_argument("--perspective")
    add_resolution_args(list_questions)
    list_questions.set_defaults(func=cmd_list_questions)
    match_questions = sub.add_parser("match-questions")
    match_questions.add_argument("--project", required=True)
    match_questions.add_argument("--text-file")
    match_questions.add_argument("--text")
    match_questions.add_argument("--include-resolved", action="store_true")
    add_resolution_args(match_questions)
    match_questions.set_defaults(func=cmd_match_questions)
    resolve_question = sub.add_parser("resolve-question")
    resolve_question.add_argument("--project", required=True)
    resolve_question.add_argument("--id", required=True)
    resolve_question.add_argument("--resolution-file", required=True)
    resolve_question.add_argument("--resolved-by-note")
    add_resolution_args(resolve_question)
    resolve_question.set_defaults(func=cmd_resolve_question)
    migrate = sub.add_parser("migrate-legacy")
    migrate.add_argument("--project", required=True)
    migrate.add_argument("--legacy-root")
    add_resolution_args(migrate)
    migrate.set_defaults(func=cmd_migrate_legacy)
    migrate_v3 = sub.add_parser("migrate-v3")
    migrate_v3.add_argument("--project", required=True)
    migrate_v3.add_argument("--dry-run", action="store_true")
    add_resolution_args(migrate_v3)
    migrate_v3.set_defaults(func=cmd_migrate_v3)
    register = sub.add_parser("register-project")
    register.add_argument("--project", required=True)
    register.add_argument("--project-root", required=True)
    register.add_argument("--name")
    register.add_argument("--alias", action="append")
    register.add_argument("--source", action="append")
    register.add_argument("--registry-file")
    register.set_defaults(func=cmd_register_project)
    unregister = sub.add_parser("unregister-project")
    unregister.add_argument("--project", required=True)
    unregister.add_argument("--registry-file")
    unregister.set_defaults(func=cmd_unregister_project)
    list_projects = sub.add_parser("list-projects")
    list_projects.add_argument("--registry-file")
    list_projects.set_defaults(func=cmd_list_projects)
    registry_doctor = sub.add_parser("registry-doctor")
    registry_doctor.add_argument("--registry-file")
    registry_doctor.set_defaults(func=cmd_registry_doctor)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
